Repository antvis/util, pull requests merged in 2019-10, with the labels that each got.

#24 feat(matrix): transfrom null matrix
  packages/matrix-util/__tests__/unit/matrix-spec.js
  packages/matrix-util/package.json
  packages/matrix-util/src/transform.ts
Labels: PR: unreviewed, enhancement

#25 feat(version): update version of matrix-util
  packages/matrix-util/package.json
Labels: PR: unreviewed, enhancement

#26 fix(path-util): fix path-util type define
  packages/path-util/package.json
  tsconfig.json
Labels: PR: reviewed-approved, bug

#27 fix: missing @types/mocha definition for torch
  package.json
Labels: PR: reviewed-approved, bug

#28 fix(memoize): when key is object, cache fail
  packages/util/__tests__/unit/memorize-spec.js
  packages/util/package.json
  packages/util/src/memoize.ts
Labels: PR: unreviewed
