Repository antvis/util, pull requests merged in 2019-09, with the labels that each got.

#19 `condition` can be string[]
  packages/util/src/group.ts
Labels: PR: reviewed-changes-requested

#20 fix: mocha ts definition
  tsconfig.json
Labels: PR: unreviewed, bug

#21 Revert "fix: mocha ts definition"
  tsconfig.json
Labels: PR: unreviewed, bug

#22 build: support esm for tree-shaking
  .eslintignore
  .gitignore
  package.json
  packages/color-util/package.json
  packages/dom-util/package.json
  packages/matrix-util/package.json
  packages/path-util/package.json
  packages/util/package.json
  tsconfig.json
  tslint.json
Labels: PR: reviewed-approved, build
