Repository antvis/util, pull requests merged in 2020-04, with the labels that each got.

#35 perf: 将较常用的方法中的遍历方法改为 for
  packages/util/src/filter.ts
  packages/util/src/get-range.ts
  packages/util/src/group-by.ts
  packages/util/src/group-to-map.ts
  packages/util/src/map.ts
  packages/util/src/values-of-key.ts
Labels: PR: reviewed-changes-requested, performance

#37 refactor: use gl-matrix as dependence
  packages/matrix-util/package.json
  packages/matrix-util/src/mat3.ts
  packages/matrix-util/src/vec2.ts
  packages/matrix-util/src/vec3.ts
Labels: PR: reviewed-changes-requested, refactor

#38 Revert "refactor: use gl-matrix as dependence"
  packages/matrix-util/package.json
  packages/matrix-util/src/mat3.ts
  packages/matrix-util/src/vec2.ts
  packages/matrix-util/src/vec3.ts
Labels: PR: reviewed-changes-requested, refactor

#39 docs(version): revert
  packages/matrix-util/package.json
Labels: PR: unreviewed, documentation

#41 fix(path-util): endTangent shoule be correct
  packages/path-util/__tests__/unit/path-2-segments-spec.js
  packages/path-util/src/path-2-segments.ts
Labels: PR: reviewed-approved, bug

#42 refactor(gl-matrix): 删除覆盖的方法,使用新的 export 语法
  packages/matrix-util/__tests__/unit/matrix-spec.js
  packages/matrix-util/package.json
  packages/matrix-util/src/index.ts
  packages/matrix-util/src/mat3.ts
  packages/matrix-util/src/transform.ts
  packages/matrix-util/src/vec2.ts
  packages/matrix-util/src/vec3.ts
Labels: PR: reviewed-changes-requested, refactor

#43 feat(transform): change left multiply
  packages/matrix-util/__tests__/unit/matrix-spec.js
  packages/matrix-util/package.json
  packages/matrix-util/src/mat3.ts
  packages/matrix-util/src/vec2.ts
Labels: PR: reviewed-changes-requested, enhancement
