Repository antvis/util, pull requests merged in 2021-02, with the labels that each got.

#58 feat: add a util to calculate max and min number & omit
  package.json
  packages/util/__tests__/unit/max-spec.js
  packages/util/__tests__/unit/min-spec.js
  packages/util/__tests__/unit/omit-spec.js
  packages/util/package.json
  packages/util/src/get-range.ts
  packages/util/src/index.ts
  packages/util/src/max.ts
  packages/util/src/min.ts
  packages/util/src/omit.ts
  packages/util/src/reduce.ts
  packages/util/src/types/index.ts
Labels: PR: partially-approved

#59 chore: add ci
  .github/workflows/build.yml
  package.json
  packages/color-util/package.json
  packages/dom-util/package.json
  packages/matrix-util/package.json
  packages/path-util/package.json
  packages/util/package.json
Labels: PR: unreviewed

#60 perf(uniq): perf fo uniq function
  packages/util/__tests__/unit/uniq-spec.js
  packages/util/package.json
  packages/util/src/group-to-map.ts
  packages/util/src/uniq.ts
Labels: PR: unreviewed

#61 fix(min): min, max should use Math function
  packages/util/__tests__/unit/get-range-spec.js
  packages/util/__tests__/unit/max-spec.js
  packages/util/__tests__/unit/min-spec.js
  packages/util/package.json
  packages/util/src/max.ts
  packages/util/src/min.ts
Labels: PR: reviewed-approved
